---
blank_issues_enabled: false
contact_links:
  - name: Material Design 3 Next.js Template Community Support
    url: https://github.com/CardoPixel/md3-nextjs-template/issues
    about: Please ask and answer questions here.
